// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpixtlnlimqnlldnrbal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwaXh0bG5saW1xbmxsZG5yYmFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MjA0NzUsImV4cCI6MjA2ODA5NjQ3NX0.KfRJltrpXyb7eNRLxsJmsM4d13yVhZrXLA99a1bkurM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});