// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ziqhqdorqfowubjrchyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InppcWhxZG9ycWZvd3VianJjaHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTQxODcsImV4cCI6MjA3MTUzMDE4N30.y-e3MujtjNYixhC2B2ukL5ou7LKTR3uIbFrpGZJJcrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});